# Generated by Django 1.10 on 2016-08-25 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("accounts", "0001_initial")]

    operations = [migrations.RemoveField(model_name="user", name="date_of_birth")]
