# Generated by Django 3.2a1 on 2021-02-04 12:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_planning_hours_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="_features",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="features",
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE audit_logged_actions
            SET row_data=row_data || hstore('_features', '{}')
            WHERE table_name='accounts_user';
            """,
            "",
        ),
    ]
