# Generated by Django 3.2a1 on 2021-02-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20210204_1350"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="enforce_same_week_logging",
        ),
    ]
