# Generated by Django 3.2.4 on 2021-08-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_coffeepairings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_employment",
            field=models.DateField(
                blank=True, null=True, verbose_name="date of employment"
            ),
        ),
    ]
