# Generated by Django 3.2.4 on 2021-08-18 08:21

from django.db import migrations


FORWARDS = """
CREATE TEMPORARY TABLE date_of_employment AS
WITH
employments AS (
  SELECT
    user_id,
    date_from,
    date_until
  FROM awt_employment
  WHERE percentage>0
  ORDER BY date_from
),
ends AS (
  SELECT
    user_id,
    array_agg(date_until + 1) AS ends
  FROM employments
  GROUP BY user_id
),
earliest AS (
  SELECT
    user_id,
    -- The latest start which ...
    MAX(date_from) AS start
  FROM employments
  LEFT JOIN ends USING (user_id)
  -- ... has no ending employment preceeding it (one day difference)
  WHERE date_from <> ALL(ends.ends)
  GROUP BY user_id
)
SELECT u.id, earliest.start
FROM accounts_user u
LEFT JOIN earliest ON u.id=earliest.user_id
WHERE earliest.start IS NOT NULL
;
UPDATE accounts_user
SET date_of_employment=date_of_employment.start
FROM date_of_employment
WHERE accounts_user.id=date_of_employment.id
;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_user_date_of_employment"),
    ]

    operations = [migrations.RunSQL(FORWARDS, "")]
