# Generated by Django 3.2.8 on 2021-11-30 10:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_auto_20210818_1021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeepairings",
            name="users",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), size=None, verbose_name="users"
            ),
        ),
    ]
