# Generated by Django 3.2.12 on 2022-03-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_coffeepairings_users"),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT audit_audit_table('accounts_user', ARRAY['password', 'last_login', 'token']);"
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                default="", editable=False, max_length=100, verbose_name="token"
            ),
            preserve_default=False,
        ),
    ]
