# Generated by Django 5.2.1 on 2025-05-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_user_pinned_projects"),
        ("projects", "0030_search_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pinned_services",
            field=models.ManyToManyField(
                blank=True, to="projects.service", verbose_name="pinned services"
            ),
        ),
    ]
