# Generated by Django 6.0a1 on 2025-09-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_user_pinned_services"),
        ("deals", "0007_attributegroup_show_on_overview"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialistfield",
            name="value_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="deals.valuetype",
                verbose_name="value type",
            ),
        ),
    ]
