# Generated by Django 6.0.3 on 2026-03-29 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_specialistfield_value_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialistfield",
            name="expected_hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="expected hourly rate",
            ),
        ),
    ]
