# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 21:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("activities", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="duration",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Duration in hours (if applicable).",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="duration",
            ),
        )
    ]
