# Generated by Django 2.1.7 on 2019-02-28 12:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("activities", "0002_auto_20190226_2248")]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="duration",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Duration in hours (if applicable).",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
                verbose_name="duration",
            ),
        )
    ]
