# Generated by Django 2.1.7 on 2019-02-28 15:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("activities", "0003_auto_20190228_1327")]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="duration",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Duration in hours (if applicable).",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
                verbose_name="duration",
            ),
        )
    ]
