# Generated by Django 2.1.7 on 2019-03-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("activities", "0003_auto_20190304_2247")]

    operations = [
        migrations.RemoveField(model_name="activity", name="duration"),
        migrations.RemoveField(model_name="activity", name="time"),
        migrations.AddField(
            model_name="activity",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
    ]
