# Generated by Django 3.0rc1 on 2019-11-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_auto_20190312_0943"),
    ]

    operations = [
        migrations.DeleteModel(name="Activity",),
    ]
