# Generated by Django 3.0.2 on 2020-01-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Accruals", new_name="MonthlyAccrual"),
    ]
