# Generated by Django 5.1.4 on 2025-01-06 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0002_costcenter"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreezeDate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                ("up_to", models.DateField(verbose_name="freeze up to")),
            ],
            options={
                "verbose_name": "freeze date",
                "verbose_name_plural": "freeze dates",
            },
        ),
        migrations.RunSQL(
            "SELECT audit_audit_table('reporting_freezedate');",
            "",
        ),
    ]
