# Generated by Django 3.0.4 on 2020-03-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logbook", "0016_auto_20191210_1537"),
        ("timer", "0002_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="timestamp",
            name="logged_hours",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logbook.LoggedHours",
                verbose_name="logged hours",
            ),
        ),
    ]
