# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20160828_0959'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='project',
        ),
        migrations.DeleteModel(
            name='Release',
        ),
    ]
