# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160918_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-priority', 'position', 'pk'), 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
    ]
