# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160918_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',), 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
