# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0010_auto_20160927_0916")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="_code",
            field=models.IntegerField(default=0, verbose_name="code"),
            preserve_default=False,
        )
    ]
