# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoices", "0005_auto_20160924_1350")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="liable_to_vat",
            field=models.BooleanField(
                default=True,
                help_text="For example invoices to foreign institutions are not liable to VAT.",
                verbose_name="liable to VAT",
            ),
        )
    ]
