# Generated by Django 3.2a1 on 2021-02-21 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planning", "0004_planningrequest_is_provisional"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivedRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "declined_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="declined at"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planning.planningrequest",
                        verbose_name="planning request",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "received request",
                "verbose_name_plural": "received requests",
                "ordering": ["-pk"],
            },
        ),
        migrations.RunSQL(
            """
INSERT INTO planning_receivedrequest (created_at, request_id, user_id)
SELECT NOW(), planningrequest_id, user_id
FROM planning_planningrequest_receivers;
            """,
            "",
        ),
    ]
