# Generated by Django 3.2a1 on 2021-02-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0005_auto_20210221_1147"),
    ]

    operations = [
        migrations.RemoveField(model_name="PlanningRequest", name="receivers"),
    ]
