# Generated by Django 3.2a1 on 2021-02-21 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planning", "0006_auto_20210221_1150"),
    ]

    operations = [
        migrations.AddField(
            model_name="planningrequest",
            name="receivers",
            field=models.ManyToManyField(
                related_name="received_planning_requests",
                through="planning.ReceivedRequest",
                to=settings.AUTH_USER_MODEL,
                verbose_name="receivers",
            ),
        ),
        migrations.AddField(
            model_name="receivedrequest",
            name="reason",
            field=models.TextField(blank=True, verbose_name="reason"),
        ),
    ]
