# Generated by Django 3.2rc1 on 2021-04-29 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planning", "0008_alter_receivedrequest_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedwork",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounts.user",
                verbose_name="created by",
            ),
            preserve_default=False,
        ),
        migrations.RunSQL("update planning_plannedwork set created_by_id=user_id", ""),
        migrations.RunSQL(
            "update audit_logged_actions set row_data=row_data || hstore('created_by_id', row_data -> 'user_id') where table_name='planning_plannedwork'",
            "",
        ),
    ]
