# Generated by Django 3.2rc1 on 2021-03-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0008_alter_receivedrequest_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="receivedrequest",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="receivedrequest",
            name="request",
        ),
        migrations.RemoveField(
            model_name="receivedrequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="plannedwork",
            name="request",
        ),
        migrations.DeleteModel(
            name="PlanningRequest",
        ),
        migrations.DeleteModel(
            name="ReceivedRequest",
        ),
    ]
