# Generated by Django 3.2rc1 on 2021-04-06 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0019_auto_20200523_0929"),
        ("planning", "0009_auto_20210327_1609"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedwork",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "milestone",
                "verbose_name_plural": "milestones",
                "ordering": ["date"],
            },
        ),
        migrations.RunSQL("UPDATE planning_plannedwork SET created_by_id=user_id", ""),
    ]
