# Generated by Django 3.2rc1 on 2021-04-29 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0009_plannedwork_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedwork',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.user', verbose_name='created by'),
        ),
    ]
