# Generated by Django 3.2rc1 on 2021-04-29 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_servicetype_color"),
        ("projects", "0019_auto_20200523_0929"),
        ("planning", "0011_plannedwork_service_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "milestone",
                "verbose_name_plural": "milestones",
                "ordering": ["date"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="receivedrequest",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="receivedrequest",
            name="request",
        ),
        migrations.RemoveField(
            model_name="receivedrequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="plannedwork",
            name="request",
        ),
        migrations.AddField(
            model_name="plannedwork",
            name="is_provisional",
            field=models.BooleanField(default=False, verbose_name="is provisional"),
        ),
        migrations.DeleteModel(
            name="PlanningRequest",
        ),
        migrations.DeleteModel(
            name="ReceivedRequest",
        ),
        migrations.AddField(
            model_name="plannedwork",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planning.milestone",
                verbose_name="milestone",
            ),
        ),
        migrations.RunSQL("select audit_audit_table('planning_milestone');", ""),
    ]
