# Generated by Django 3.2rc1 on 2021-04-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0012_plannedwork_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedwork",
            name="is_provisional",
            field=models.BooleanField(default=False, verbose_name="is provisional"),
        ),
    ]
