# Generated by Django 3.2.2 on 2021-05-16 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0013_publicholiday"),
    ]

    operations = []
