# Generated by Django 3.2rc1 on 2021-04-28 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0013_plannedwork_is_provisional"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedwork",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planning.milestone",
                verbose_name="milestone",
            ),
        ),
    ]
