# Generated by Django 3.2.4 on 2021-07-29 09:41

from decimal import Decimal

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_auto_20200523_0929"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0005_servicetype_color"),
        ("planning", "0014_auto_20210516_1510"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="estimated_total_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="planned hours",
            ),
        ),
        migrations.CreateModel(
            name="ExternalWork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "weeks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(), size=None, verbose_name="weeks"
                    ),
                ),
                (
                    "provided_by",
                    models.CharField(max_length=200, verbose_name="provided by"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="planning.milestone",
                        verbose_name="milestone",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_work",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="services.servicetype",
                        verbose_name="primary service type",
                    ),
                ),
            ],
            options={
                "verbose_name": "external work",
                "verbose_name_plural": "external work",
                "ordering": ["-pk"],
            },
        ),
    ]
