# Generated by Django 3.2.4 on 2021-08-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_organization_is_archived'),
        ('planning', '0015_auto_20210729_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='phase_starts_on',
            field=models.DateField(blank=True, null=True, verbose_name='phase starts on'),
        ),
        migrations.AlterField(
            model_name='externalwork',
            name='provided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_work', to='contacts.organization', verbose_name='provided by'),
        ),
    ]
