# Generated by Django 3.2.4 on 2021-08-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0015_auto_20210729_1141"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="phase_starts_on",
            field=models.DateField(
                null=True, verbose_name="succeeds a phase and starts on"
            ),
        ),
    ]
