# Generated by Django 3.2.8 on 2021-11-16 12:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0016_auto_20210802_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalwork',
            name='color_override',
            field=colorfield.fields.ColorField(blank=True, default='', max_length=18, verbose_name='override default coloring'),
        ),
        migrations.AddField(
            model_name='plannedwork',
            name='color_override',
            field=colorfield.fields.ColorField(blank=True, default='', max_length=18, verbose_name='override default coloring'),
        ),
    ]
