# Generated by Django 3.2.4 on 2021-08-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0016_milestone_phase_starts_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="phase_starts_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="succeeds a phase and starts on"
            ),
        ),
    ]
