# Generated by Django 5.2 on 2025-05-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0016_auto_20210802_1938"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicholiday",
            name="date",
            field=models.DateField(unique=True, verbose_name="date"),
        ),
    ]
