# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 11:36
from __future__ import unicode_literals

from django.db import migrations
from workbench.tools.search import migration_sql


class Migration(migrations.Migration):

    dependencies = [("projects", "0003_auto_20160917_1324")]

    operations = [
        migrations.RunSQL(
            "SELECT audit_audit_table('projects_task');"
            "SELECT audit_audit_table('projects_comment');",
            "",
        ),
        migrations.RunSQL(*migration_sql("projects_task", "title, description")),
    ]
