# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("projects", "0006_auto_20160918_1035")]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("-priority", "pk"),
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        )
    ]
