# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 07:31
from __future__ import unicode_literals

from collections import defaultdict
import itertools

from django.db import migrations


def forward(apps, schema_editor):
    codes = defaultdict(lambda: itertools.count(start=1))
    Project = apps.get_model("projects", "Project")

    for project in Project.objects.order_by("created_at"):
        project._code = next(codes[project.created_at.year])
        project.save()


class Migration(migrations.Migration):

    dependencies = [("projects", "0011_project__code")]

    operations = [migrations.RunPython(forward)]
