# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logbook", "0006_auto_20190226_2206"),
        ("projects", "0012_auto_20160927_0931"),
    ]

    operations = [
        migrations.RemoveField(model_name="attachment", name="task"),
        migrations.RemoveField(model_name="comment", name="created_by"),
        migrations.RemoveField(model_name="comment", name="task"),
        migrations.RemoveField(model_name="task", name="created_by"),
        migrations.RemoveField(model_name="task", name="owned_by"),
        migrations.RemoveField(model_name="task", name="project"),
        migrations.RemoveField(model_name="task", name="service"),
        migrations.DeleteModel(name="Attachment"),
        migrations.DeleteModel(name="Comment"),
        migrations.DeleteModel(name="Task"),
    ]
