# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 21:57
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0014_auto_20190226_2249")]

    operations = [
        migrations.AddField(
            model_name="service",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="cost",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="effort_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="effort hours",
            ),
            preserve_default=False,
        ),
    ]
