# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 16:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0015_auto_20190226_2257")]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="effort_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="effort hours",
            ),
        )
    ]
