# Generated by Django 2.1.7 on 2019-02-28 12:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0016_auto_20190227_1754")]

    operations = [
        migrations.AlterField(
            model_name="effort",
            name="hours",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
                verbose_name="hours",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="effort_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
                verbose_name="effort hours",
            ),
        ),
    ]
