# Generated by Django 2.1.7 on 2019-02-28 15:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0017_auto_20190228_1327")]

    operations = [
        migrations.AlterField(
            model_name="effort",
            name="hours",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
                verbose_name="hours",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="effort_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
                verbose_name="effort hours",
            ),
        ),
    ]
