# Generated by Django 2.1.7 on 2019-03-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("projects", "0018_auto_20190228_1657")]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="offers.Offer",
                verbose_name="offer",
            ),
        )
    ]
