# Generated by Django 3.2.14 on 2022-09-09 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_auto_20220909_2028"),
    ]

    operations = [
        migrations.AddField(
            model_name="internaltype",
            name="is_selectable",
            field=models.BooleanField(default=True, verbose_name="is selectable"),
        ),
        migrations.AlterField(
            model_name="project",
            name="internal_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_selectable": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="projects.internaltype",
                verbose_name="internal type",
            ),
        ),
    ]
