# Generated by Django 3.2.14 on 2022-09-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_auto_20220910_0930"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internaltype",
            name="assigned_users",
        ),
    ]
