# Generated by Django 3.2.15 on 2022-11-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_internaltype_description"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE projects_project SET internal_type_id=NULL WHERE type != 'internal'"
        ),
    ]
