# Generated by Django 5.0.6 on 2024-06-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0028_auto_20221121_1351"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internaltype",
            name="ordering",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="ordering"
            ),
        ),
    ]
