# Generated by Django 6.0.3 on 2026-04-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0030_search_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="external_reference",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="external reference"
            ),
        ),
    ]
