# Generated by Django 6.0.5 on 2026-05-19 07:36

from django.db import migrations

from workbench.tools import search


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0031_external_reference"),
    ]

    operations = [
        migrations.RunSQL(
            search.fts(
                "projects_service", ["title", "description", "external_reference"]
            )
        ),
        migrations.RunSQL("update projects_service set id=id"),
    ]
