# Generated by Django 6.1.1 on 2026-09-21 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0034_budgettransfer"),
    ]

    operations = [
        migrations.RunSQL("SELECT audit_audit_table('projects_budgettransfer');", "")
    ]
