# Generated by Django 5.2a1 on 2025-02-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("webhook_url", models.URLField(verbose_name="webhook url")),
                (
                    "forward_fields",
                    models.JSONField(blank=True, verbose_name="forward fields"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhooks",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookForward",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.CharField(max_length=200, verbose_name="content object"),
                ),
                (
                    "forwarded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="forwarded at"
                    ),
                ),
                ("forward_data", models.JSONField(verbose_name="forward data")),
                (
                    "forwarding_last_failed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="forwarding last failed at"
                    ),
                ),
                (
                    "forwarding_retry_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="forwarding retry count"
                    ),
                ),
                (
                    "forwarding_error_log",
                    models.TextField(blank=True, verbose_name="forwarding error log"),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="webhooks.webhookconfiguration",
                    ),
                ),
            ],
        ),
    ]
