# Generated by Django 1.11.16 on 2018-11-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("calendar", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="app",
            name="slug",
            field=models.SlugField(default="", unique=True, verbose_name="slug"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="app",
            name="ordering",
            field=models.IntegerField(default=0, verbose_name="ordering"),
        ),
    ]
