# Generated by Django 1.11.16 on 2018-11-21 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calendar", "0003_auto_20181121_1003"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="app",
            options={
                "ordering": ["ordering"],
                "verbose_name": "app",
                "verbose_name_plural": "apps",
            },
        ),
        migrations.AlterModelOptions(
            name="dayofweekdefault",
            options={
                "verbose_name": "day of week default",
                "verbose_name_plural": "day of week defaults",
            },
        ),
        migrations.AlterModelOptions(
            name="presence",
            options={"verbose_name": "presence", "verbose_name_plural": "presences"},
        ),
        migrations.AlterField(
            model_name="day",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="days",
                to=settings.AUTH_USER_MODEL,
                verbose_name="handled by",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="presence", unique_together=set([("app", "user", "year")])
        ),
    ]
