# Generated by Django 2.1.3 on 2018-11-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("calendar", "0004_auto_20181121_1717")]

    operations = [
        migrations.CreateModel(
            name="CompanyHoliday",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="date from")),
                ("date_until", models.DateField(verbose_name="date until")),
            ],
            options={
                "verbose_name": "company holiday",
                "verbose_name_plural": "company holidays",
            },
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("day", models.DateField(unique=True, verbose_name="day")),
            ],
            options={
                "verbose_name": "public holiday",
                "verbose_name_plural": "public holidays",
            },
        ),
    ]
