# Generated by Django 2.1.3 on 2020-03-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar", "0005_companyholiday_publicholiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="is_paused",
            field=models.BooleanField(default=False, verbose_name="is paused"),
        ),
    ]
