# Generated by Django 2.1.7 on 2019-03-04 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("projects", "0001_initial"), ("offers", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offers",
                to="projects.Project",
                verbose_name="project",
            ),
        )
    ]
