# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("offers", "0003_auto_20160917_2057")]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={
                "ordering": ("-offered_on",),
                "verbose_name": "offer",
                "verbose_name_plural": "offers",
            },
        ),
        migrations.AddField(
            model_name="offer",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created at"
            ),
        ),
    ]
