# Generated by Django 2.2.4 on 2019-08-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("offers", "0004_auto_20190321_1449")]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="show_service_details",
            field=models.BooleanField(
                default=True, verbose_name="show service details"
            ),
        )
    ]
