# Generated by Django 3.2b1 on 2021-03-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0010_offer__fts"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="work_completed_on",
            field=models.DateField(
                blank=True,
                help_text="Fill in this field if you want to prohibit further logging on this offers' services.",
                null=True,
                verbose_name="work completed on",
            ),
        ),
    ]
