# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 21:49
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logbook", "0007_auto_20190226_2249"),
        ("offers", "0010_auto_20190226_2055"),
    ]

    operations = [
        migrations.RemoveField(model_name="cost", name="service"),
        migrations.AlterUniqueTogether(name="effort", unique_together=set([])),
        migrations.RemoveField(model_name="effort", name="service"),
        migrations.RemoveField(model_name="effort", name="service_type"),
        migrations.RemoveField(model_name="service", name="offer"),
        migrations.AlterField(
            model_name="offer",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="discount",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="subtotal",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("7.7"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="tax rate",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="total",
            ),
        ),
        migrations.DeleteModel(name="Cost"),
        migrations.DeleteModel(name="Effort"),
        migrations.DeleteModel(name="Service"),
    ]
