# Generated by Django 3.2.12 on 2022-04-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0011_offer_work_completed_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="is_budget_retainer",
            field=models.BooleanField(
                default=False,
                help_text="The offer is only used for budgeting; services have to be created later when rendering actual work.",
                verbose_name="is budget retainer",
            ),
        ),
    ]
