# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("offers", "0011_auto_20190226_2249")]

    operations = [
        migrations.RemoveField(model_name="offer", name="closed_at"),
        migrations.AddField(
            model_name="offer",
            name="closed_on",
            field=models.DateField(blank=True, null=True, verbose_name="closed on"),
        ),
    ]
