# Generated by Django 3.2.14 on 2022-09-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0012_offer_is_budget_retainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "In preparation"),
                    (15, "Service group"),
                    (20, "Offered"),
                    (30, "Accepted"),
                    (40, "Declined"),
                ],
                default=10,
                verbose_name="status",
            ),
        ),
    ]
