# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 14:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('rendered_on', models.DateField(default=datetime.date.today, verbose_name='rendered on')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='hours')),
                ('description', models.TextField(verbose_name='description')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='invoices.Invoice', verbose_name='invoice')),
                ('rendered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renderedservices', to=settings.AUTH_USER_MODEL, verbose_name='rendered by')),
            ],
            options={
                'verbose_name': 'rendered service',
                'verbose_name_plural': 'rendered services',
                'ordering': ('-rendered_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RequiredService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_effort', models.DecimalField(decimal_places=2, help_text='The original estimate.', max_digits=5, verbose_name='estimated effort')),
                ('offered_effort', models.DecimalField(decimal_places=2, help_text='Effort offered to the customer.', max_digits=5, verbose_name='offered effort')),
                ('planning_effort', models.DecimalField(decimal_places=2, help_text='Effort for planning. This value should reflect the current  state of affairs also when work is already in progress.', max_digits=5, verbose_name='planning effort')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.ServiceType', verbose_name='service type')),
            ],
            options={
                'verbose_name': 'required service',
                'verbose_name_plural': 'required services',
                'ordering': ('service_type',),
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.PositiveIntegerField(choices=[(10, 'unscheduled'), (20, 'scheduled'), (30, 'started'), (40, 'finished'), (50, 'delivered'), (60, 'accepted'), (15, 'rejected')], default=10, verbose_name='status')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('due_on', models.DateField(blank=True, help_text='This field should be left empty most of the time.', null=True, verbose_name='due on')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='offers.Offer', verbose_name='offer')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owned by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='projects.Project', verbose_name='project')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='projects.Release', verbose_name='release')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
                'ordering': ('release', 'position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='requiredservice',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requiredservices', to='stories.Story', verbose_name='story'),
        ),
        migrations.AddField(
            model_name='renderedservice',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renderedservices', to='stories.Story', verbose_name='story'),
        ),
        migrations.AlterUniqueTogether(
            name='requiredservice',
            unique_together=set([('story', 'service_type')]),
        ),
    ]
