# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('position', 'id'), 'verbose_name': 'story', 'verbose_name_plural': 'stories'},
        ),
        migrations.RemoveField(
            model_name='story',
            name='release',
        ),
    ]
