# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20160828_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Inbox'), (20, 'Backlog'), (30, 'In progress'), (40, 'Ready for test'), (50, 'Done'), (60, 'Archived')], default=10, verbose_name='status'),
        ),
    ]
