# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20160917_2112'),
        ('stories', '0004_auto_20160828_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renderedservice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='renderedservice',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='renderedservice',
            name='rendered_by',
        ),
        migrations.RemoveField(
            model_name='renderedservice',
            name='story',
        ),
        migrations.AlterUniqueTogether(
            name='requiredservice',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='requiredservice',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='requiredservice',
            name='story',
        ),
        migrations.RemoveField(
            model_name='story',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='story',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='story',
            name='project',
        ),
        migrations.RemoveField(
            model_name='story',
            name='requested_by',
        ),
        migrations.DeleteModel(
            name='RenderedService',
        ),
        migrations.DeleteModel(
            name='RequiredService',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
