# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 21:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="servicetype",
            name="billing_per_hour",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="billing per hour",
            ),
        )
    ]
