# Generated by Django 2.1.7 on 2019-02-28 12:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0002_auto_20190226_2248")]

    operations = [
        migrations.AlterField(
            model_name="servicetype",
            name="billing_per_hour",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
                verbose_name="billing per hour",
            ),
        )
    ]
