# Generated by Django 3.2rc1 on 2021-03-27 14:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_auto_20190915_1249"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", max_length=18, verbose_name="color"
            ),
        ),
        migrations.AlterField(
            model_name="servicetype",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="color",
            ),
        ),
    ]
