# Generated by Django 2.1.7 on 2019-03-04 11:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0004_auto_20190228_1657")]

    operations = [
        migrations.AlterField(
            model_name="servicetype",
            name="billing_per_hour",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="billing per hour",
            ),
        )
    ]
