# Generated by Django 3.2rc1 on 2021-03-27 14:46

from django.db import migrations

import colorfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_auto_20190915_1249"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="color",
            field=colorfield.fields.ColorField(
                default="#20c997", max_length=18, verbose_name="color"
            ),
        ),
    ]
