gettext("%sh per week")
gettext("%sh/day")
gettext("(closed)")
gettext("(declined)")
gettext("(not accepted yet)")
gettext("Absences")
gettext("Activity")
gettext("Add planned work")
gettext("Capacity per week")
gettext("Delta")
gettext("Go to the project")
gettext("No project selected")
gettext("No services available")
gettext("Not part of an offer")
gettext("OK")
gettext("Open logged hours form")
gettext("Overwrite seconds")
gettext("Planned hours per week")
gettext("Remove")
gettext("Requested hours per week")
gettext("Reset")
gettext("Select or search project...")
gettext("Select service...")
gettext("Send to logbook")
gettext("Settings")
gettext("This week")
gettext("Timer")
gettext("Today")
gettext("Unable to open the form")
gettext("Unable to submit the logbook entry")
gettext("Week %s")
gettext("What outcome do you seek?")
gettext("is provisional")
pgettext("one letter Friday", "F")
pgettext("one letter Monday", "M")
pgettext("one letter Saturday", "S")
pgettext("one letter Sunday", "S")
pgettext("one letter Thursday", "T")
pgettext("one letter Tuesday", "T")
pgettext("one letter Wednesday", "W")
pgettext("provisional", "prov.")
