gettext("(closed)")
gettext("(declined)")
gettext("(not accepted yet)")
gettext("Absences and public holidays")
gettext("Activity")
gettext("Add planned work")
gettext("Break")
gettext("Concurrent absences")
gettext("Days")
gettext("Description")
gettext("Efforts")
gettext("is provisional")
gettext("Logged hours")
gettext("milestones")
gettext("No project selected")
gettext("No services available")
gettext("Not part of an offer")
gettext("Of which provisional")
gettext("OK")
gettext("Open logged hours form")
gettext("Overwrite elapsed time (h:m:s or m:s or seconds)")
gettext("Overwrite time (h:m:s or m:s or seconds)")
gettext("Planned hours per week")
gettext("Remaining capacity per week")
gettext("Remove")
gettext("Reset")
gettext("Save break")
gettext("Select or search project...")
gettext("Select service...")
gettext("Send to logbook")
gettext("Settings")
gettext("Start break")
gettext("This week")
gettext("Timer")
gettext("Today")
gettext("Unable to open the form")
gettext("Unable to submit the logbook entry")
gettext("Week %s")
gettext("What outcome do you seek?")
gettext(m)
pgettext("one letter Friday", "F")
pgettext("one letter Monday", "M")
pgettext("one letter Saturday", "S")
pgettext("one letter Sunday", "S")
pgettext("one letter Thursday", "T")
pgettext("one letter Tuesday", "T")
pgettext("one letter Wednesday", "W")
pgettext("provisional", "prov.")
