# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("invoices", "0001_initial")]

    operations = []
