# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoices", "0008_auto_20190226_2055")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="_code",
            field=models.IntegerField(default=0, verbose_name="code"),
            preserve_default=False,
        )
    ]
