# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoices", "0010_auto_20190226_2248")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="closed_on",
            field=models.DateField(blank=True, null=True, verbose_name="closed on"),
        ),
        migrations.RunSQL("UPDATE invoices_invoice SET closed_on=closed_at"),
        migrations.RemoveField(model_name="invoice", name="closed_at"),
    ]
