# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20190227_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_notice',
            field=models.TextField(blank=True, verbose_name='payment notice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='closed_on',
            field=models.DateField(blank=True, help_text='Payment date for paid invoices, date of replacement or cancellation otherwise.', null=True, verbose_name='closed on'),
        ),
    ]
