# Generated by Django 3.2.7 on 2021-10-06 13:37

import datetime as dt

from django.db import migrations
from django.db.models import F, Sum


def forwards(apps, schema_editor):
    Invoice = apps.get_model("invoices", "Invoice")
    ProjectedInvoice = apps.get_model("invoices", "ProjectedInvoice")

    queryset = (
        Invoice.objects.filter(project__isnull=False)
        .order_by()
        .annotate(gross_margin=F("total_excl_tax") - F("third_party_costs"))
        .values("project")
        .annotate(Sum("gross_margin"))
    )

    for row in queryset:
        if row["gross_margin__sum"] <= 0:
            continue

        ProjectedInvoice.objects.create(
            project_id=row["project"],
            invoiced_on=dt.date.today(),
            gross_margin=row["gross_margin__sum"],
            description="Automatisch bestimmt aus vergangenen Rechnungen",
        )


def backwards(apps, schema_editor):
    ProjectedInvoice = apps.get_model("invoices", "ProjectedInvoice")

    ProjectedInvoice.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0023_projectedinvoice"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
