# Generated by Django 3.2.14 on 2022-09-08 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0024_auto_20211006_1537"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectedinvoice",
            options={
                "ordering": ["invoiced_on"],
                "verbose_name": "projected gross margin",
                "verbose_name_plural": "projected gross margin",
            },
        ),
    ]
