# Generated by Django 6.1.1 on 2026-10-02 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0028_invoice_postpone_reminders_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectedinvoice",
            name="gross_margin",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Invoice total excl. tax minus third party costs incl. tax.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="gross margin",
            ),
        ),
    ]
