# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20160917_2027'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT audit_audit_table('offers_service');"
            "SELECT audit_audit_table('offers_effort');"
            "SELECT audit_audit_table('offers_cost');",
        ),
    ]
