# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20160922_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='approved_hours',
            new_name='_approved_hours',
        ),
    ]
