# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_offer_disable_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='disable_tax',
        ),
        migrations.AddField(
            model_name='offer',
            name='liable_to_vat',
            field=models.BooleanField(default=True, help_text='For example invoices to foreign institutions are not liable to VAT.', verbose_name='liable to VAT'),
        ),
    ]
