# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0010_auto_20190226_2055"),
        ("logbook", "0005_auto_20160925_1706"),
    ]

    operations = [
        migrations.RemoveField(model_name="loggedhours", name="task"),
        migrations.AddField(
            model_name="loggedhours",
            name="service",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loggedhours",
                to="offers.Service",
                verbose_name="service",
            ),
            preserve_default=False,
        ),
    ]
