# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 21:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("logbook", "0006_auto_20190226_2206"),
        ("projects", "0014_auto_20190226_2249"),
    ]

    operations = [
        migrations.RunSQL("delete from logbook_loggedhours"),
        migrations.RunSQL("delete from logbook_loggedcost"),
        migrations.AlterField(
            model_name="loggedcost",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=None,
                help_text="Total incl. tax for third-party costs.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="cost",
            ),
        ),
        migrations.AlterField(
            model_name="loggedcost",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loggedcosts",
                to="projects.Service",
                verbose_name="service",
            ),
        ),
        migrations.AlterField(
            model_name="loggedhours",
            name="hours",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="hours",
            ),
        ),
        migrations.AlterField(
            model_name="loggedhours",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loggedhours",
                to="projects.Service",
                verbose_name="service",
            ),
        ),
    ]
