# Generated by Django 2.1.7 on 2019-02-28 15:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("logbook", "0008_auto_20190228_1327")]

    operations = [
        migrations.AlterField(
            model_name="loggedhours",
            name="hours",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
                verbose_name="hours",
            ),
        )
    ]
