# Generated by Django 2.1.7 on 2019-03-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("logbook", "0009_auto_20190228_1657")]

    operations = [
        migrations.AlterModelOptions(
            name="loggedcost",
            options={
                "ordering": ("-rendered_on", "-created_at"),
                "verbose_name": "logged cost",
                "verbose_name_plural": "logged costs",
            },
        )
    ]
