# Generated by Django 6.0a1 on 2025-09-19 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "__first__"),
        ("expenses", "0004_exchangerates"),
        ("invoices", "0027_invoice_archived_at"),
        ("invoices", "0027_invoice_archived_at"),
        ("logbook", "0020_auto_20200511_1419"),
        ("projects", "0030_search_fix"),
        ("projects", "0030_search_fix"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="loggedhours",
            name="logbook_log_rendere_ea492e_idx",
        ),
        migrations.AddIndex(
            model_name="loggedhours",
            index=models.Index(
                models.OrderBy(models.F("rendered_on"), descending=True),
                name="logbook_hours_rendered_on",
            ),
        ),
        migrations.AddIndex(
            model_name="loggedcost",
            index=models.Index(
                models.OrderBy(models.F("rendered_on"), descending=True),
                name="logbook_cost_rendered_on",
            ),
        ),
    ]
