# Generated by Django 3.2a1 on 2021-02-06 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0004_auto_20201017_1016"),
    ]

    operations = [
        migrations.RunSQL(
            """
UPDATE audit_logged_actions
SET
    row_data=row_data - '{fts_document,_fts}'::text[],
    changed_fields=changed_fields - '{fts_document,_fts}'::text[]
WHERE
    row_data ?| '{fts_document,_fts}'::text[]
    OR changed_fields ?| '{fts_document,_fts}'::text[]
            """
        ),
    ]
