# Generated by Django 2.1.7 on 2019-02-28 12:40

from django.db import migrations
from workbench.tools.search import migration_sql


fwd, back = migration_sql("contacts_organization", "name, notes")


class Migration(migrations.Migration):

    dependencies = [("contacts", "0001_initial")]

    operations = [
        migrations.RunSQL(back),
        migrations.RunSQL(fwd),
        migrations.RunSQL(
            "UPDATE contacts_organization"
            " SET fts_document=contacts_organization_fts_document(id)"
        ),
    ]
