# Generated by Django 2.1.7 on 2019-03-04 17:28

from django.db import migrations, models
import django_countries.fields

from workbench.tools.search import migration_sql


FORWARD, BACKWARD = migration_sql(
    "contacts_person", "given_name, family_name, address, notes"
)


class Migration(migrations.Migration):

    dependencies = [("contacts", "0002_auto_20190228_1340")]

    operations = [migrations.RunSQL(BACKWARD)]
