# Generated by Django 2.1.7 on 2019-03-04 20:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [("contacts", "0003_auto_20190304_1828")]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["given_name", "family_name"],
                "verbose_name": "person",
                "verbose_name_plural": "people",
            },
        ),
        migrations.RemoveField(model_name="person", name="full_name"),
        migrations.RemoveField(model_name="postaladdress", name="postal_address"),
        migrations.AddField(
            model_name="person",
            name="family_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="family name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="given_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="given name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postaladdress",
            name="address_suffix",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="address suffix"
            ),
        ),
        migrations.AddField(
            model_name="postaladdress",
            name="city",
            field=models.CharField(default="", max_length=100, verbose_name="city"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postaladdress",
            name="country",
            field=django_countries.fields.CountryField(default="CH", max_length=2),
        ),
        migrations.AddField(
            model_name="postaladdress",
            name="house_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="house number"
            ),
        ),
        migrations.AddField(
            model_name="postaladdress",
            name="postal_address_override",
            field=models.TextField(
                blank=True,
                help_text="Completely overrides the postal address if set.",
                verbose_name="override",
            ),
        ),
        migrations.AddField(
            model_name="postaladdress",
            name="postal_code",
            field=models.CharField(
                default="", max_length=20, verbose_name="postal code"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postaladdress",
            name="street",
            field=models.CharField(default="", max_length=100, verbose_name="street"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="E.g. Sir/Madam",
                max_length=100,
                verbose_name="address",
            ),
        ),
    ]
