# Generated by Django 2.1.7 on 2019-03-04 21:11

from django.db import migrations
from workbench.tools.search import migration_sql


FORWARD, BACKWARD = migration_sql(
    "contacts_person", "given_name, family_name, address, notes"
)


class Migration(migrations.Migration):

    dependencies = [("contacts", "0004_auto_20190304_2140")]

    operations = [migrations.RunSQL(FORWARD, BACKWARD)]
