# Generated by Django 2.1.7 on 2019-03-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("deals", "0001_initial")]

    operations = [
        migrations.RunSQL(
            "SELECT audit_audit_table('deals_deal');"
            "SELECT audit_audit_table('deals_stage');",
            "",
        ),
        migrations.RunSQL(*migration_sql("deals_deal", "title, description")),
    ]
