# Generated by Django 3.0.3 on 2020-02-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0002_auto_20200219_1234"),
    ]

    operations = [
        migrations.AddField(
            model_name="valuetype",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="is archived"),
        ),
    ]
