# Generated by Django 2.1.7 on 2019-03-21 13:48

from django.db import migrations

from workbench.tools import search


class Migration(migrations.Migration):

    dependencies = [("deals", "0002_auto_20190304_2247")]

    operations = [
        migrations.RunSQL(search.drop_old_shit("deals_deal")),
        migrations.RunSQL(search.create_structure("deals_deal")),
        migrations.RunSQL(search.fts("deals_deal", ["title", "description"])),
    ]
