# Generated by Django 3.0rc1 on 2019-11-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0005_delete_activity"),
        ("deals", "0003_auto_20190321_1448"),
    ]

    operations = [
        migrations.DeleteModel(name="Deal",),
        migrations.DeleteModel(name="Stage",),
    ]
