# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("deals", "0004_auto_20190226_2248")]

    operations = [
        migrations.AlterModelOptions(
            name="deal",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "deal",
                "verbose_name_plural": "deals",
            },
        ),
        migrations.RemoveField(model_name="deal", name="closed_at"),
        migrations.AddField(
            model_name="deal",
            name="closed_on",
            field=models.DateField(blank=True, null=True, verbose_name="closed on"),
        ),
    ]
