# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_auto_20160924_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedcost',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loggedcosts', to='offers.Service', verbose_name='service'),
        ),
    ]
