# Generated by Django 2.1.7 on 2019-03-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("invoices", "0008_auto_20190312_1254")]

    operations = [
        migrations.CreateModel(
            name="Accrual",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(verbose_name="month")),
                (
                    "accrual",
                    models.IntegerField(
                        help_text="Percentage of down payment invoice for which the work has already been done.",
                        verbose_name="accrual",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.Invoice",
                        verbose_name="invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "accrual",
                "verbose_name_plural": "accruals",
                "ordering": ["-month", "-invoice_id"],
            },
        )
    ]
