# Generated by Django 3.0.2 on 2020-01-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accruals", "0002_auto_20190325_1003"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="accrual", unique_together=None,),
        migrations.RemoveField(model_name="accrual", name="invoice",),
        migrations.DeleteModel(name="CutoffDate",),
        migrations.DeleteModel(name="Accrual",),
    ]
