# Generated by Django 3.2.6 on 2021-08-18 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("awt", "0012_auto_20201012_1433"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacationDaysOverride",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="year")),
                (
                    "days",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="days"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacation_days_overrides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "vacation days override",
                "verbose_name_plural": "vacation days overrides",
                "ordering": ["year"],
                "unique_together": {("user", "year")},
            },
        ),
        migrations.RunSQL(
            "SELECT audit_audit_table('awt_vacationdaysoverride');",
            "",
        ),
    ]
