# Generated by Django 3.2.8 on 2021-12-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awt", "0014_vacationdaysoverride_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacationdaysoverride",
            name="type",
            field=models.CharField(
                choices=[("absolute", "absolute"), ("relative", "relative")],
                default="absolute",
                max_length=10,
                verbose_name="type",
            ),
            preserve_default=False,
        ),
    ]
