# Generated by Django 2.1.7 on 2019-03-08 09:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoices", "0005_auto_20190307_0925"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountStatement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="processed at"
                    ),
                ),
                ("statement", models.BinaryField(verbose_name="statement")),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="title"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "account statement",
                "verbose_name_plural": "account statements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="reference number"
                    ),
                ),
                ("value_date", models.DateField(verbose_name="value date")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="total",
                    ),
                ),
                (
                    "payment_notice",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="payment notice"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "account_statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="credit_control.AccountStatement",
                        verbose_name="account statement",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="invoices.Invoice",
                        verbose_name="invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "credit entry",
                "verbose_name_plural": "credit entries",
                "ordering": ["value_date", "pk"],
            },
        ),
    ]
