# Generated by Django 2.1.7 on 2019-03-08 16:52

from django.db import migrations

from workbench.tools.search import migration_sql


class Migration(migrations.Migration):

    dependencies = [("credit_control", "0001_initial")]

    operations = [
        migrations.RunSQL(
            "SELECT audit_audit_table('credit_control_creditentry');", ""
        ),
        migrations.RunSQL(
            *migration_sql(
                "credit_control_creditentry",
                "reference_number, total, payment_notice, notes",
            )
        ),
    ]
