# Generated by Django 3.2.12 on 2022-03-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_control", "0008_creditentry__fts"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
    ]
